config/routes.rb
Rails.application.routes.draw do

  resources :things
  resources :rigs
  resources :laboratories do
	member do
		put 'published'
	end
  end
  resources :gateways

  get 'laboratories/:id/ui-designer', :to => 'laboratories#ui_designer', :as => 'ui_designer'

  get 'laboratories/:id/get_form/:type', :to => 'laboratories#get_form', :as => 'ui_designer_get_form'

  get 'l/:id', :to => 'laboratories#l_session', :as => 'laboratory_session'

  get 'experiments', :to => 'laboratories#experiments', :as => 'experiments'

  post 'mqtt', :to => 'gateways#mqtt_publish', :as => 'mqtt_publish'

  get 'api/get_chart_data', :to => 'laboratories#get_chart_data', :as => 'get_chart_data'

  get 'api/get_log_data', :to => 'rigs#get_log_data', :as => 'get_log_data'

  #get 'laboratory/new', :to => 'laboratories#create', :as => 'create_laboratory'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/thing.rb
class Thing < ActiveRecord::Base
  has_and_belongs_to_many :laboratories
  belongs_to :gateway
  has_many :thing_logs
  accepts_nested_attributes_for :thing_logs

  enum thing_type: [:switch, :analog_reader, :temperature_sensor, :motor, :servo, :sensorTag]
 end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_thing, only: [:show, :edit, :update, :destroy, :ui_designer]
  
  respond_to :html

  def index
    @things = Thing.all
    respond_with(@things)
  end

  def show
  	@topics = @thing.thing_logs.order("created_at DESC").map(&:topic).uniq
	#@topics = Thing.includes(:thing_logs).find(params[:id]).thing_logs.find_by_sql("select topic, max(updated_at) as latest from thing_logs group by topic")
	#.uniq(|t| t[:topic])
    respond_with(@thing)
  end

  def new
    @thing = Thing.new
    respond_with(@thing)
  end

  def edit
  end

  def create
    @thing = Thing.new(thing_params)
    flash[:notice] = 'Thing was successfully created.' if @thing.save
    respond_with(@thing)
  end

  def update
    flash[:notice] = 'Thing was successfully updated.' if @thing.update(thing_params)
    respond_with(@thing)
  end

  def destroy
    @thing.destroy
    respond_with(@thing)
  end

  private
    def set_thing
      @thing = Thing.includes(:thing_logs).find(params[:id])
    end

    def thing_params
      params[:thing].permit(:thing_type, :thing_addr, :thing_hash, :thing_log_ids => [], :laboratory_ids => [])
    end
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/things/_form.html.erb
<%= simple_form_for(@thing) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :thing_name %>
    <div class="form-group">
		<%= f.label :thing_type %>
		<%= f.select(:thing_type, Thing.thing_types.keys.map {|type| [type.titleize,type]}, {}, class: 'form-control') %>
    </div>
    <%= f.input :thing_hash %>
    <%= f.input :gateway_id %>	
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  
<% end %>

app/views/things/edit.html.erb
<div class="container">
	<h1>Editing Thing</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @thing %> |
	<%= link_to 'Back', things_path %>
</div?

app/views/things/index.html.erb
<div class="container">

<h1 class="text-center">Available Things</h1>
<hr>

<table class="table">
  <thead>
    <tr>
      <th>Thing Name</th>
      <th>Thing Identifier</th>
      <th>Thing Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @things.each do |thing| %>
      <tr>
        <td><%= thing.thing_name %></td>
        <td><%= thing.thing_hash %></td>
        <td><%= thing.thing_type%></td>
        <td><%= link_to 'Show', thing %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<div class="container">
  <h1>
    <%= @thing.thing_name %>
    <small>( Last updated: <%= @thing.updated_at.strftime(fmt='%d-%m-%y %H:%M') %>)</small>
  </h1>
  <p>
    <label>Identifier:</label>
    <%= @thing.thing_hash %>
  </p>

  <p>
    <label>Type:</label>
    <%= @thing.thing_type == 1 ? 'Chartable Data' : 'Not Chartable Data' %>
  </p>

  <hr>
  <div class="buttons">
    <%= link_to 'Edit Thing', edit_thing_path(@thing), class: 'btn btn-primary btn-lg' %>
  </div>
  <hr>

  <h2>Thing Data Available</h2>
  <table class="table">
    <thead>
		<th>Topic Name</th>
    </thead>
    <tbody>
      <% @topics.each do |t| %>
      <tr>
        <td><%= t %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>