config/routes.rb
Rails.application.routes.draw do

  resources :things
  resources :rigs
  resources :laboratories do
	member do
		put 'published'
	end
  end
  resources :gateways

  get 'laboratories/:id/ui-designer', :to => 'laboratories#ui_designer', :as => 'ui_designer'

  get 'laboratories/:id/get_form/:type', :to => 'laboratories#get_form', :as => 'ui_designer_get_form'

  get 'l/:id', :to => 'laboratories#l_session', :as => 'laboratory_session'

  get 'experiments', :to => 'laboratories#experiments', :as => 'experiments'

  post 'mqtt', :to => 'gateways#mqtt_publish', :as => 'mqtt_publish'

  get 'api/get_chart_data', :to => 'laboratories#get_chart_data', :as => 'get_chart_data'

  get 'api/get_log_data', :to => 'rigs#get_log_data', :as => 'get_log_data'

  #get 'laboratory/new', :to => 'laboratories#create', :as => 'create_laboratory'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/laboratory.rb
class Laboratory < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :things
  has_many :thing_logs, :through => :things
  has_many :thing_widgets
  validates :title, presence: true
  enum lab_type: [:publish_only, :interactive]
end

app/controllers/laboratories_controller.rb
require 'mqtt'
class LaboratoriesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_laboratory, only: [:show, :edit, :update, :destroy, :ui_designer, :l_session, :published]
  before_action :defined_widgets, only: [:ui_designer, :l_session]

  respond_to :html

  def index
    @laboratories = current_user.laboratories
    respond_with(@laboratories)
  end
  
  def show
    @thing_logs = @laboratory.thing_logs.includes(:thing) 
	@things = @laboratory.things
    respond_with(@thing_logs, @things)
  end
  
  def new
    @available_things = Thing.where(status: "registered")
    @laboratory = Laboratory.new
    respond_with(@laboratory, @available_things)
  end 

  def edit
  end
  
  def ui_designer
    
	# remove dead things
    #@laboratory.things.each do |thing|
    #  if thing.thing_logs.last == nil
    #    thing.delete
    #  elsif thing.thing_logs.last.created_at < 15.seconds.ago
    #    thing.delete
    #  end
    #end
	
    #@things = @laboratory.things
    #@switchable_things = @laboratory.things.where(thing_type: 0)
	#@servo_things = @laboratory.things.where(thing_type: 2)
	#@motor_things = @laboratory.things.where(thing_type: 3)
	#@chartable_things = @laboratory.things.where.not(thing_type: 0).includes(:thing_logs)
	
	@chartable_logs = @laboratory.thing_logs.includes(:thing).where("thing_type != ?",0)
	
  end
  
  
  def l_session
    redirect_to experiments_path, alert: 'This experiment is not available at the moment, please try again later...' if @laboratory.things.count == 0
    @ui_json = JSON.parse(@laboratory.ui_json)
  end
  
  def get_chart_data
    @thing = Thing.find(params[:thing_id])
	@thing_log = params[:thing_log_id]

    @time = Time.at(params[:from].to_i / 1000.0)

    @data = @thing.thing_logs.where('id = ? AND updated_at > ?', @thing_log, @time).pluck(:data)

    #@data.each do |val|
	#	puts val
	#	ret_val.push({x: val[1].to_f * 1000, y: val[0].to_f})
    #end

	puts @data
    #render :json => ret_val
	render :json => @data
  end

  def get_log_data
    @thing = Thing.find(params[:thing_id])
    @pin = params[:pin]

    @time = Time.at(params[:from].to_i / 1000.0)

    @data = @thing.thing_logs.where('pin = ? AND created_at > ?', @pin, @time).pluck(:data, :created_at).last

    ret_val = nil

    ret_val = {time: @data[1].strftime('%H:%M:%S'), value: @data[0]} unless @data.nil?

    render :json => ret_val
  end
  
  
  def create
    @laboratory = current_user.laboratories.new(laboratory_params)
    flash[:notice] = 'Laboratory was successfully created.' if @laboratory.save
	redirect_to laboratory: "show"
    #respond_with(@laboratory)
  end
  
  def update
    flash[:notice] = 'Laboratory was successfully updated.' if @laboratory.update(laboratory_params)
    respond_with(@laboratory)
  end
  
  def destroy
    @laboratory.destroy
    respond_with(@laboratory)
  end
  
  def experiments
    @experiments = Laboratory.where(published: true)
  end  
  
  def published
	@laboratory = Laboratory.find(params[:id])
    flash[:notice] = 'Laboratory was successfully published.' if @laboratory.update(:published => params[:published])
    respond_with(@laboratory)
  end
	
  private
    def set_laboratory
      @laboratory = Laboratory.includes(:thing_logs).find(params[:id])
    end
	
	def laboratory_params
      params.require(:laboratory).permit(:title, :description, :pdf_file, :ui_json, :password, :published, :thing_ids => [])
    end
	
	def defined_widgets
      @defined_widgets = {
        "line-chart"=> {title: 'Line chart', image: '/widgets/line-chart.png', form: 'chart-form'},
        #"bar-chart"=> {title: 'Bar chart', image: '/widgets/bar-chart.png', #form: 'chart-form'},
        #"switch"=> {title: 'Switch', image: '/widgets/switch.png', form: #'switch-form'},
        #"data-log"=> {title: 'Data Log', image: '/widgets/data-log.png', form: #'data-log-form'},
        #"value"=> {title: 'Value', image: '/widgets/value.png', form: #'value-form'},
        #"motor"=> {title: 'Motor', image: '/widgets/motor.png', form: #'motor-form'},
        #"servo"=> {title: 'Servo', image: '/widgets/servo.png', form: #'servo-form'}
      }
    end

	
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/views/laboratories/_form.html.erb
  <%= simple_form_for(@laboratory)  do |f| %>
	<h2>Laboratory Details</h2>

	<%= f.error_notification %>	
	
    <%= f.label "Enter laboratory name: " %>
	<%= f.text_field :title,  include_blank: "Choose a laboratory name", required: true %>
	<br>
    <%= f.label "Enter laboratory description:  " %>
	<%= f.text_area :description %>

  
	<h2>Available Things</h2>
	
	Select the Things to add to this laboratory:
	<br>
    <%= f.collection_check_boxes(:thing_ids, Thing.where(status: "registered"), :id, :thing_hash) do |b| %>
		<div class="row">
			<%= b.label(class: "check_box") do %>
				<div class="col-xs-2">
					<%= b.check_box(class: "check_box") %>
				</div>

				<div class="col-xs-10">
					<%= b.object.thing_name %> (<%= b.object.thing_hash %>)
				</div>       
			<% end %>
		</div>	
  	<% end %>
  
	<div class="form-actions">
		<%= f.button :submit, class: 'btn btn-primary' %>
	</div>
  
  <% end %>

app/views/laboratories/_line_chart.html.erb
<li class="line-chart-widget" id="<%= widget['id'] %>" data-row="<%= widget['row'] %>" data-col="<%= widget['col'] %>" data-sizex="<%= widget['size_x'] %>" data-sizey="<%= widget['size_y'] %>">
  <div class="chart" id="container-<%= widget['id'] %>" </div>
</li>

<script>
$(function () {

    var lastUpdated = (new Date()).getTime();
	
	var thing_topic = "<%= widget['settings'].select{|s| s['name'] == 'thing_topic'}.first['value'] %>";
	var thing_topic_split = thing_topic.split("_");

    var thing_id = thing_topic_split[0];
    var thing_log_id = thing_topic_split[1];

    $(document).ready(function () {
        Highcharts.setOptions({
            global: {
                useUTC: false
            }
        });

        $('#container-<%= widget['id'] %>').highcharts({
            chart: {
                type: 'spline',
                animation: Highcharts.svg, // don't animate in old IE
                marginRight: 10,
                events: {
                    load: function () {

                        //set up the updating of the chart each second
                        var series = this.series;
						
                        setInterval(function () {
                          $.ajax({
                            url: '/api/get_chart_data',
                            data: {thing_id: thing_id, thing_log_id: thing_log_id, from: lastUpdated},
                            success: function(data) {
								for (var i = 0; i < data.length; i++) 
								{
									var x1,y1,name1;
									var i=0;
									for (var key in data[0]) {
										x1 = new Date(data[0].updated);
										if (key != "updated")
										{
											y1 = data[0][key];
											name1 = key;
											//console.log(name1, y1, i );
											if (series[i].data.length >= 10)
												series[i].addPoint({x: x1.getTime(), y: y1, name: name1}, true, true);
											else
												series[i].addPoint({x:x1.getTime(), y:y1, name: name1}, true, false);
										}
										i++;
									}	
								}
                              lastUpdated = (new Date()).getTime();
                            }
                          })

                        }, 1000);
                    }
                }
            },
            title: {
                text: '<%= widget['settings'].select{|s| s['name'] == 'name'}.first['value'] %>'
            },
            xAxis: {
                title: {
                    text: '<%= widget['settings'].select{|s| s['name'] == 'xAxis'}.first['value'] %>'
               
			   },
                type: 'datetime',
                tickPixelInterval: 150,
				labels: {
					formatter: function(){
						var thedate=Highcharts.dateFormat('%b %e %H:%M', this.value);
                    return thedate;
					}
				}
            },
            yAxis: {
                title: {
                    text: '<%= widget['settings'].select{|s| s['name'] == 'yAxis'}.first['value'] %>'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    return '<b> Value for: ' + this.point.name + '</b><br/>' +
                        Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' +
                        Highcharts.numberFormat(this.y, 2);
                }
            },
            legend: {
                enabled: false,
		    },
            exporting: {
                enabled: false
            },
            series: [{
                name: 'Series 0',
                data: []
				}, {
				name: 'Series 1',
				data: []
				}, {
				name: 'Series 2',
				data: []
				}]
        });
    });
});


</script>

app/views/laboratories/_line_chart_test.html.erb
<li class="line-chart-widget" id="<%= widget['id'] %>" data-row="<%= widget['row'] %>" data-col="<%= widget['col'] %>" data-sizex="<%= widget['size_x'] %>" data-sizey="<%= widget['size_y'] %>">
  <div class="chart" id="container-<%= widget['id'] %>" </div>
</li>

<script>
$(function () {

    var lastUpdated = (new Date()).getTime();
	
	var thing_topic = "<%= widget['settings'].select{|s| s['name'] == 'thing_topic'}.first['value'] %>";
	var thing_topic_split = thing_topic.split("_");

    var thing_id = thing_topic_split[0];
    var thing_log_id = thing_topic_split[1];

    $(document).ready(function () {
        Highcharts.setOptions({
            global: {
                useUTC: false
            }
        });

        $('#container-<%= widget['id'] %>').highcharts({
            chart: {
                type: 'spline',
                animation: Highcharts.svg, // don't animate in old IE
                marginRight: 10,
                events: {
                    load: function () {

                        //set up the updating of the chart each second
                        var series = this.series;
						
                        setInterval(function () {
                          $.ajax({
                            url: '/api/get_chart_data',
                            data: {thing_id: thing_id, thing_log_id: thing_log_id, from: lastUpdated},
                            success: function(data) {
								for (var i = 0; i < data.length; i++) 
								{
									var x1,y1,name1;
									var i=0;
									for (var key in data[0]) {
										x1 = new Date(data[0].updated);
										if (key != "updated")
										{
											y1 = data[0][key];
											name1 = key;
											//console.log(name1, y1, i );
											if (series[i].data.length >= 10)
												series[i].addPoint({x: x1.getTime(), y: y1, name: name1}, true, true);
											else
												series[i].addPoint({x:x1.getTime(), y:y1, name: name1}, true, false);
										}
										i++;
									}	
								}
                              lastUpdated = (new Date()).getTime();
                            }
                          })

                        }, 1000);
                    }
                }
            },
            title: {
                text: '<%= widget['settings'].select{|s| s['name'] == 'name'}.first['value'] %>'
            },
            xAxis: {
                title: {
                    text: '<%= widget['settings'].select{|s| s['name'] == 'xAxis'}.first['value'] %>'
               
			   },
                type: 'datetime',
                tickPixelInterval: 150,
				labels: {
					formatter: function(){
						var thedate=Highcharts.dateFormat('%b %e %H:%M', this.value);
                    return thedate;
					}
				}
            },
            yAxis: {
                title: {
                    text: '<%= widget['settings'].select{|s| s['name'] == 'yAxis'}.first['value'] %>'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    return '<b> Value for: ' + this.point.name + '</b><br/>' +
                        Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' +
                        Highcharts.numberFormat(this.y, 2);
                }
            },
            legend: {
                enabled: false
		    },
            exporting: {
                enabled: false
            },
            series: [{
                name: 'Series 0',
                data: []
				}, {
				name: 'Series 1',
				data: []
				}, {
				name: 'Series 2',
				data: []
				}]
        });
    });
});

/**
 * Request data from the server, add it to the graph and set a timeout 
 * to request again
 */
function requestData() {
    var series = this.series;

	$.ajax({
		url: '/api/get_chart_data',
        data: {thing_id: thing_id, thing_log_id: thing_log_id, from: lastUpdated},
		success: function(data) {
			for (var i = 0; i < data.length; i++) 
				{
					var x1,y1,name1;
					for (var key in data[0]) {
						x1 = new Date(data[0].updated);
						if (key != "updated")
						{
							y1 = data[0][key];
							name1 = key;
							//console.log(name1, y1, i );
							shift = series[i].data.length > 20; // shift if the series is 
																// longer than 20
							series[i].addPoint({x: x1.getTime(), y: y1, name: name1}, true, shift);
						}
					}	
				}
            }
		})
            setTimeout(requestData, 1000);    
        },
        cache: false
    });
}

</script>

app/views/laboratories/_switch.html.erb
<li class="switch-widget" id="<%= widget['id'] %>" data-row="<%= widget['row'] %>" data-col="<%= widget['col'] %>" data-sizex="<%= widget['size_x'] %>" data-sizey="<%= widget['size_y'] %>">
  <% if Thing.find(widget['settings'].select{|s| s['name'] == 'thingModule'}.first['value']).thing_datas.last.data.split(',')[widget['settings'].select{|s| s['name'] == 'pin'}.first['value'].to_i].to_i == 1 %>
    <img class="switch" data-on="true" src="/widgets/ui/switch_on.png" />
  <% else %>
    <img class="switch" data-on="false" src="/widgets/ui/switch_off.png" />
  <% end %>
  <h4><%= widget['settings'].select{|s| s['name'] == 'name'}.first['value'] %></h4>
</li>

<script>
  $('.switch-widget#<%= widget['id'] %> .switch').on('click', function() {
    if ($(this).data('on') == true) {

      $.ajax({
        method: 'post',
        url: '/mqtt',
        data: {
          'laboratory_hash': '<%= @laboratory.laboratory_hash %>',
          's_address': '<%= Thing.find(widget['settings'].select{|s| s['name'] == 'slaveModule'}.first['value']).s_addr %>',
          's_command': 0,
          's_value': <%= widget['settings'].select{|s| s['name'] == 'pin'}.first['value'] %>
          }
      })

      $(this).attr('src', '/widgets/ui/switch_off.png');
      $(this).data('on', false);
    } else {

      $.ajax({
        method: 'post',
        url: '/mqtt',
        data: {
          'rig_hash': '<%=  @rig.rig_hash %>',
          's_address': '<%= SlaveModule.find(widget['settings'].select{|s| s['name'] == 'slaveModule'}.first['value']).s_addr %>',
          's_command': 1,
          's_value': <%= widget['settings'].select{|s| s['name'] == 'pin'}.first['value'] %>
          }
      })
      $(this).attr('src', '/widgets/ui/switch_on.png')
      $(this).data('on', true);
    }
  });
</script>

app/views/laboratories/create.html.erb
<h1>Laboratories#create</h1>
<p>Find me in app/views/laboratories/create.html.erb</p>

app/views/laboratories/edit.html.erb
<div class="container">
  <h1>Configuring the Laboratory</h1>

  <%= render 'form' %>

  <hr>

</div>

app/views/laboratories/experiments.html.erb
<div class="container">
  <h1 class="text-center">Experiments</h1>
  <hr>

  <% @experiments.each do |experiment| %>
    <div class="experiment thumbnail col-md-3 text-center">
      <h3><a href="<%= laboratory_session_path(experiment.id) %>"><%= experiment.title %></a></h3>
      <p><small>created by <%= experiment.user.email %></small></p>
      <p><small><%= experiment.description%></small></p>
    </div>
  <% end %>
</div>

app/views/laboratories/index.html.erb
<div class="container">

<h1 class="text-center">Existing Laboratories</h1>
<hr>

<%= link_to 'Create a new laboratory', new_laboratory_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @laboratories.each do |laboratory| %>
      <tr>
        <td><%= laboratory.title.titleize %></td>
        <td><%= laboratory.description %></td>
        <td><%= laboratory.published ? 'Published' : 'Private' %></td>
        <td><%= link_to 'Show', laboratory %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/laboratories/l_session.html.erb
<%= javascript_tag do %>
	window.definedWidgets = JSON.parse('<%= raw @defined_widgets.to_json %>');
  window.uiJSON = JSON.parse('<%= raw @laboratory.ui_json %>');
<% end %>


<!-- render the ui_json and bind the elements to the hardware modules -->
<div class="col-md-10 col-md-offset-1">
  <div class="gridster thumbnail" id="canvas">
    <!-- widgets goes inside the ul -->
    <ul>
      <% @ui_json.each do |widget| %>
      <%= render partial: widget['type'].gsub('-', '_'), locals: {widget: widget} %>
      <% end %>
    </ul>

  </div>
</div>



<script>
  $(function() {
    var gridster = $(".gridster ul").gridster({
      widget_margins: [10, 10],
      widget_base_dimensions: [250, 165]
      // resize: {enabled: true},
    }).data('gridster').disable();
  });
</script>

app/views/laboratories/new.html.erb
<div class="container">
  <h1>Register New Laboratory</h1>
  <p>Please enter your laboratory details and select the Things to add to your laboratory from the list below:</p>
	<small> TO DO: complete the form with Laboratory details and suitable layout </small>
  
  <%= render 'form' %>
  
</div>
	
	

app/views/laboratories/show.html.erb
<div class="container">
  <h1>
    <%= @laboratory.title %>
    <small>( Last updated: <%= @laboratory.updated_at.strftime(fmt='%d-%m-%y %H:%M') %>)</small>
  </h1>
  <p>
    <label>Description:</label>
    <%= @laboratory.description %>
  </p>

  <p>
    <label>Status:</label>
    <%= @laboratory.published ? 'Published' : 'Private' %>
  </p>

  <p>
    <label>Password Protected:</label>
    <%= @laboratory.password.present?.to_s.titleize %>
  </p>

  <hr>
  <div class="buttons">
    <%= link_to 'Edit Laboratory', edit_laboratory_path(@laboratory), class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Design Laboratory UI', ui_designer_path(@laboratory), class: 'btn btn-warning btn-lg' %>
	<% if @laboratory.published %>
		<%= link_to 'Unpublish Laboratory', published_laboratory_path(@laboratory.id, :published => false), :method => :put, class: 'btn btn-primary btn-lg' %>
    <% else %>
		<%= link_to 'Publish Laboratory', published_laboratory_path(@laboratory.id, :published => true), :method => :put, class: 'btn btn-warning btn-lg' %>
    <% end %>
  </div>
  <hr>


  <h2>Things and data available for this laboratory</h2>
  <table class="table">
    <thead>
      <th>Thing Name</th>
      <th>Identifier</th>
      <th>Available Data</th>
    </thead>
    <tbody>
      <% @things.each do |thing| %>
		<tr>
			<td><%= thing.thing_name %></td>
			<td><%= thing.thing_hash %></td>
			<td>
				<% thing.thing_logs.map(&:topic).uniq.each do |topic| %>
				<%= topic.titleize %>
			<% end %>
		</tr>
      <% end %>
    </tbody>
  </table>
  
  <%= link_to 'Back', laboratories_path, class: 'btn btn-default' %>
</div>

app/views/laboratories/ui_designer.html.erb
<%= javascript_tag do %>
	window.definedWidgets = JSON.parse('<%= raw @defined_widgets.to_json %>');
  <% if @laboratory.ui_json.nil? %>
    window.uiJSON = {};
  <% else %>
    window.uiJSON = JSON.parse('<%= raw @laboratory.ui_json.gsub("'", %q(\\\')) %>');
  <% end %>
<% end %>

<div>

  <div class="col-md-2" id="side-bar">
    <h3>Wigdets</h3>

    <small>Drag and drop the widgets onto the canvas on the right.</small>

    <hr>

    <% @defined_widgets.each do |key, value| %>
      <div class="row">
        <img class="thumbnail defined-widget" src="<%= value[:image] %>" id="<%= key %>"/>
      </div>
    <% end %>

    <hr>

    <div class="row centerize">
      <%= simple_form_for(@laboratory) do |f| %>
        <%= f.hidden_field :ui_json %>
      <% end %>

      <a class="btn btn-success btn-lg" id="save-ui">Save</a>
      <a class="btn btn-danger btn-lg" href="<%= laboratory_path(@laboratory) %>">Cancel</a>
    </div>
  </div>


  <div class="col-md-10">
    <div class="gridster thumbnail" id="canvas">
      <!-- widgets goes inside the ul -->
      <ul>
      </ul>

    </div>
  </div>

</div>

</div>
	<div class="modal fade" id="settings-modal" tabindex="-1" role="dialog" aria-labelledby="settings-modal" aria-hidden="true">
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title">Settings</h4>
		  </div>
		  <div class="modal-body">
		  

			 <form id="chart-form" style="display: none;">

			  <label for="thing_topic">Thing</label>
			  <select name="thing_topic" class="form-control">
				<% @chartable_logs.each do |t| %>
				  <option value="<%= t.thing_id %>_<%= t.id %>"><%= "Topic '#{t.topic.titleize}' on Thing '#{t.thing.thing_name}'" %></option>
				<% end %>
			  </select>
			  
			  <label for="name">Name</label>
			  <input name="name" class="form-control"></input>

			  <label for="xAxis">X Axis</label>
			  <input name="xAxis" class="form-control"></input>

			  <label for="yAxis">Y Axis</label>
			  <input name="yAxis" class="form-control"></input>

			  <label for="period">Period</label>
			  <input name="period" class="form-control" type="number"></input>

			  <label for="interval">Interval</label>
			  <input name="interval" class="form-control" type="number"></input>

			  <label for="updateRate">Update Rate</label>
			  <input name="updateRate" class="form-control" type="number"></input>

			</form>

		  </div>

		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal" id="close-settings">Close</button>
			<button type="button" class="btn btn-primary" id="save-settings">Save changes</button>
		  </div>
		</div>
	  </div>
	</div>

<script>
  $(function() {

    var widgetNextIndex = 0;

    var gridster = $(".gridster ul").gridster({
      widget_margins: [10, 10],
      widget_base_dimensions: [250, 165],
      resize: {enabled: true},
      serialize_params: function ($w, wgd) {
        return {
          id: parseInt($($w).attr('id')),
          type: $($w).data('type'),
          settings: $($w).data('settings'),
          col: wgd.col,
          row: wgd.row,
          size_x: wgd.size_x,
          size_y: wgd.size_y
        };
      }
    }).data('gridster');

    $('.defined-widget').draggable({
      revert: true
    });

    $('#canvas').droppable({
      accept: '.defined-widget',
      drop: function(event, ui) {
        var widgetType = ui.draggable.attr('id');
        while ($('.widget-in#' + widgetNextIndex).length != 0) {
          widgetNextIndex++
        }
        addWidgetToCanvas(widgetType, widgetNextIndex);
      }
    });

    rebuildWidgetsFromJson();

    // bind the save button
    $('#save-ui').on('click', function() {
      // check that all the widgets have been configured
      if ($(".widget-in.unconfigured").length > 0) {
        alert('You must configure all widgets before saving.');
      } else {
      // generate the json string and submit the form
        $('#laboratory_ui_json').val(JSON.stringify(gridster.serialize()));
        $('form.edit_laboratory').submit();
      }
    });


    // FUNCTIONS

    function rebuildWidgetsFromJson() {
      if (window.uiJSON.length > 0) {
        $.each(window.uiJSON, function() {
          addWidgetToCanvas(this.type, this.id, this.size_x, this.size_y, this.col, this.row, this.settings);
        });

        // adjust the next indea for extra widgets
        widgetNextIndex = $('.widget-in').length;
      }
    }

    function addWidgetToCanvas(widgetType, index, size_x, size_y, col, row, settings) {
      // create and add the widget to the canvas
      if (typeof size_x == 'undefined') {
        gridster.add_widget(
          '<li class="widget-in" id="' + index + '" data-type="' + widgetType + '">' +
            '<a class="btn btn-danger pull-right delete-widget">Delete</a>' +
            '<a class="btn btn-default pull-right setting-widget">Settings</a>' +
            '<img src="' + window.definedWidgets[widgetType].image + '"/>' +
          '</li>');

        $('.widget-in#' + index).addClass('unconfigured');
      } else {
        gridster.add_widget(
          '<li class="widget-in" id="' + index + '" data-type="' + widgetType + '">' +
            '<a class="btn btn-danger pull-right delete-widget">Delete</a>' +
            '<a class="btn btn-default pull-right setting-widget">Settings</a>' +
            '<img src="' + window.definedWidgets[widgetType].image + '"/>' +
          '</li>', size_x, size_y, col, row);

        $('.widget-in#' + index).data('settings', settings);
      }

      // bind delete buttons
      $('.widget-in#' + index + ' .delete-widget').on('click', function() {
        gridster.remove_widget($(this).parent());
      })

      // bind settings buttons
      $('.widget-in#' + index + ' .setting-widget').on('click', function() {
        // setup the modal form fields and buttons
        $('.modal-body form').hide();
        $('#' + window.definedWidgets[widgetType].form).show();

        var currentId = $(this).parent().attr('id');

        // repopulate fields if defined
        document.getElementById(window.definedWidgets[widgetType].form).reset();
        var values = $(this).parent().data('settings');
        if (typeof values != 'undefined') {
          for (var i = 0; i < values.length; i++) {
            $("input[name='" + values[i].name + "']").val(values[i].value);
          }
        }

        $('#save-settings').data('widgetId', currentId);
        $('#save-settings').off('click');
        $('#save-settings').on('click', function() {
          // store json data to the widget
          var thisId = $(this).data('widgetId');
          var thisForm = $('#' + window.definedWidgets[widgetType].form);

          var formData = thisForm.serializeArray();
          $('.widget-in#' + thisId).data('settings', formData);
          $('.widget-in#' + thisId).removeClass('unconfigured');

          // reset the form
          document.getElementById(window.definedWidgets[widgetType].form).reset();

          // close the modal
          $('#settings-modal').modal('hide')
        });

        // show modal
        $('#settings-modal').modal();
      })
    }

  });



</script>