config/routes.rb
Rails.application.routes.draw do

  resources :things
  resources :rigs
  resources :laboratories do
	member do
		put 'published'
	end
  end
  resources :gateways

  get 'laboratories/:id/ui-designer', :to => 'laboratories#ui_designer', :as => 'ui_designer'

  get 'laboratories/:id/get_form/:type', :to => 'laboratories#get_form', :as => 'ui_designer_get_form'

  get 'l/:id', :to => 'laboratories#l_session', :as => 'laboratory_session'

  get 'experiments', :to => 'laboratories#experiments', :as => 'experiments'

  post 'mqtt', :to => 'gateways#mqtt_publish', :as => 'mqtt_publish'

  get 'api/get_chart_data', :to => 'laboratories#get_chart_data', :as => 'get_chart_data'

  get 'api/get_log_data', :to => 'rigs#get_log_data', :as => 'get_log_data'

  #get 'laboratory/new', :to => 'laboratories#create', :as => 'create_laboratory'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>

<div class="container">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse ">
  <div class="col-md-8 col-md-offset-2">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'remotelab.club', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links_right' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li><%= link_to 'Laboratories', laboratories_path %></li>
  <li><%= link_to 'Things', things_path %></li>
  <li><%= link_to 'Gateways', gateways_path%></li>
  <li><%= link_to 'Run a lab', experiments_path %></li>
<% end %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/_navigation_links_right.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <%= current_user.email %> <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Update Profile', edit_user_registration_path %></li>
      <% if current_user.admin? %>
        <li class="divider"></li>
        <li><%= link_to 'User Management', users_path %></li>
      <% end %>
      <li class="divider"></li>
      <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "remotelab.club" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "remotelab.club" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body ng-app="remoteLabClub">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>