config/routes.rb
Rails.application.routes.draw do

  resources :things
  resources :rigs
  resources :laboratories do
	member do
		put 'published'
	end
  end
  resources :gateways

  get 'laboratories/:id/ui-designer', :to => 'laboratories#ui_designer', :as => 'ui_designer'

  get 'laboratories/:id/get_form/:type', :to => 'laboratories#get_form', :as => 'ui_designer_get_form'

  get 'l/:id', :to => 'laboratories#l_session', :as => 'laboratory_session'

  get 'experiments', :to => 'laboratories#experiments', :as => 'experiments'

  post 'mqtt', :to => 'gateways#mqtt_publish', :as => 'mqtt_publish'

  get 'api/get_chart_data', :to => 'laboratories#get_chart_data', :as => 'get_chart_data'

  get 'api/get_log_data', :to => 'rigs#get_log_data', :as => 'get_log_data'

  #get 'laboratory/new', :to => 'laboratories#create', :as => 'create_laboratory'

  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/rig.rb
class Rig < ActiveRecord::Base
  belongs_to :user
  has_many :slave_modules
  has_many :slave_widgets

  enum rig_type: [:publish_only, :interactive]
end

app/controllers/rigs_controller.rb
require 'mqtt'
class RigsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_rig, only: [:show, :edit, :update, :destroy, :ui_designer, :r_session]
  before_action :defined_widgets, only: [:ui_designer, :r_session]

  respond_to :html

  def index
    @rigs = current_user.rigs
    respond_with(@rigs)
  end

  def show

    # remove dead slaves
    @rig.slave_modules.each do |slave|
      if slave.slave_datas.last == nil
        slave.delete
      elsif slave.slave_datas.last.created_at < 15.seconds.ago
        slave.delete
      end
    end

    @slave = @rig.slave_modules
    respond_with(@rig)
  end

  def new
    @pending_rigs = Rig.where(synced: false)
    respond_with(@pending_rigs)
  end

  def edit
  end

  def ui_designer

    # remove dead slaves
    @rig.slave_modules.each do |slave|
      if slave.slave_datas.last == nil
        slave.delete
      elsif slave.slave_datas.last.created_at < 20.seconds.ago
        slave.delete
      end
    end

    @slave_modules = @rig.slave_modules
    @switchable_slaves = @rig.slave_modules.where(s_type: 0)
    @chartable_slaves = @rig.slave_modules.where.not(s_type: 0)
    @motor_slaves = @rig.slave_modules.where(s_type: 3)
    @servo_slaves = @rig.slave_modules.where(s_type: 4)
  end

  def r_session
    redirect_to experiments_path, alert: 'This experiment is not available at the moment, please try again later...' if @rig.slave_modules.count == 0
    @ui_json = JSON.parse(@rig.ui_json)
  end

  def mqtt_publish

    rig_hash = params[:rig_hash]
    slave_address = params[:s_address]
    command = params[:s_command]
    message = params[:s_value]

    topic = "rigs/#{rig_hash}/slaves/#{slave_address}/#{command}"

    MQTT::Client.connect('localhost') do |c|
      c.publish(topic, message)
    end

    render :text => 'Done'
  end

  def get_chart_data
    @slave = SlaveModule.find(params[:slave_id])
    @pin = params[:pin]

    @time = Time.at(params[:from].to_i / 1000.0)

    @data = @slave.slave_datas.where('pin = ? AND created_at > ?', @pin, @time).pluck(:data, :created_at)

    ret_val = []

    @data.each do |val|
      ret_val.push({x: val[1].to_f * 1000, y: val[0].to_f})
    end

    render :json => ret_val
  end

  def get_log_data
    @slave = SlaveModule.find(params[:slave_id])
    @pin = params[:pin]

    @time = Time.at(params[:from].to_i / 1000.0)

    @data = @slave.slave_datas.where('pin = ? AND created_at > ?', @pin, @time).pluck(:data, :created_at).last

    ret_val = nil

    ret_val = {time: @data[1].strftime('%H:%M:%S'), value: @data[0]} unless @data.nil?

    render :json => ret_val
  end

  def create
    @rig = current_user.rigs.new(rig_params)
    flash[:notice] = 'Rig was successfully created.' if @rig.save
    respond_with(@rig)
  end

  def update
    flash[:notice] = 'Rig was successfully updated.' if @rig.update(rig_params)
    respond_with(@rig)
  end

  def destroy
    @rig.destroy
    respond_with(@rig)
  end


  def experiments
    @experiments = Rig.where(published: true)
  end

  private
    def set_rig
      @rig = Rig.find(params[:id])
    end

    def rig_params
      params.require(:rig).permit(:title, :rig_type, :description, :pdf_file, :ui_json, :password)
    end

    def defined_widgets
      @defined_widgets = {
        "line-chart"=> {title: 'Line chart', image: '/widgets/line-chart.png', form: 'chart-form'},
        "bar-chart"=> {title: 'Bar chart', image: '/widgets/bar-chart.png', form: 'chart-form'},
        "switch"=> {title: 'Switch', image: '/widgets/switch.png', form: 'switch-form'},
        "data-log"=> {title: 'Data Log', image: '/widgets/data-log.png', form: 'data-log-form'},
        "value"=> {title: 'Value', image: '/widgets/value.png', form: 'value-form'},
        "motor"=> {title: 'Motor', image: '/widgets/motor.png', form: 'motor-form'},
        "servo"=> {title: 'Servo', image: '/widgets/servo.png', form: 'servo-form'}
      }
    end
end

app/helpers/rigs_helper.rb
module RigsHelper
end

app/views/rigs/_bar_chart.html.erb
<li class="bar-chart-widget" id="<%= widget['id'] %>" data-row="<%= widget['row'] %>" data-col="<%= widget['col'] %>" data-sizex="<%= widget['size_x'] %>" data-sizey="<%= widget['size_y'] %>">
  <h4><%= widget['settings'].select{|s| s['name'] == 'name'}.first['value'] %></h4>

  <canvas class="bar-chart" id="bar-chart-<%= widget['id'] %>"></canvas>

</li>


  <script>
  var data = {
      labels: ["January", "February", "March", "April", "May", "June", "July"],
      datasets: [
          {
              label: "My First dataset",
              fillColor: "rgba(220,220,220,0.5)",
              strokeColor: "rgba(220,220,220,0.8)",
              highlightFill: "rgba(220,220,220,0.75)",
              highlightStroke: "rgba(220,220,220,1)",
              data: [65, 59, 80, 81, 56, 55, 40]
          },
          {
              label: "My Second dataset",
              fillColor: "rgba(151,187,205,0.5)",
              strokeColor: "rgba(151,187,205,0.8)",
              highlightFill: "rgba(151,187,205,0.75)",
              highlightStroke: "rgba(151,187,205,1)",
              data: [28, 48, 40, 19, 86, 27, 90]
          }
      ]
  };

  var ctx = document.getElementById("bar-chart-<%= widget['id'] %>").getContext("2d");
  var myBarChart = new Chart(ctx).Bar(data);
  </script>

app/views/rigs/_form.html.erb
<%= simple_form_for(@rig) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <div class="form-group">
      <%= f.label :rig_type %>
      <%= f.select(:rig_type, Rig.rig_types.keys.map {|type| [type.titleize,type]}, {}, class: 'form-control') %>
    </div>
    <%= f.input :description %>

    <%= f.input :password %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/rigs/_line_chart.html.erb
<li class="line-chart-widget" id="<%= widget['id'] %>" data-row="<%= widget['row'] %>" data-col="<%= widget['col'] %>" data-sizex="<%= widget['size_x'] %>" data-sizey="<%= widget['size_y'] %>">
  <div class="chart" id="container-<%= widget['id'] %>" </div>
</li>

<script>
$(function () {

    var lastUpdated = (new Date()).getTime();

    var pin = <%= widget['settings'].select{|s| s['name'] == 'pin'}.first['value'] %>
    var slaveModule = <%= widget['settings'].select{|s| s['name'] == 'slaveModule'}.first['value'] %>

    $(document).ready(function () {
        Highcharts.setOptions({
            global: {
                useUTC: false
            }
        });

        $('#container-<%= widget['id'] %>').highcharts({
            chart: {
                type: 'spline',
                animation: Highcharts.svg, // don't animate in old IE
                marginRight: 10,
                events: {
                    load: function () {

                        // set up the updating of the chart each second
                        var series = this.series[0];

                        setInterval(function () {
                          $.ajax({
                            url: '/api/get_chart_data',
                            data: {slave_id: slaveModule, pin: pin, from: lastUpdated},
                            success: function(data) {
                              for (var i = 0; i < data.length; i++) {
                                if (series.data.length >= 10)
                                  series.addPoint([x: data[i].x,y: data[i].y, name: key], true, true);
                                else
                                  series.addPoint([data[i].x, data[i].y]);
                              }
                              lastUpdated = (new Date()).getTime();
                            }
                          })

                        }, 1000);
                    }
                }
            },
            title: {
                text: '<%= widget['settings'].select{|s| s['name'] == 'name'}.first['value'] %>'
            },
            xAxis: {
                title: {
                    text: '<%= widget['settings'].select{|s| s['name'] == 'xAxis'}.first['value'] %>'
                },
                type: 'datetime',
                tickPixelInterval: 150
            },
            yAxis: {
                title: {
                    text: '<%= widget['settings'].select{|s| s['name'] == 'yAxis'}.first['value'] %>'
                },
                plotLines: [{
                    value: 0,
                    width: 1,
                    color: '#808080'
                }]
            },
            tooltip: {
                formatter: function () {
                    return '<b>' + this.series.data.name + '</b><br/>' +
                        Highcharts.dateFormat('%Y-%m-%d %H:%M:%S', this.x) + '<br/>' +
                        Highcharts.numberFormat(this.y, 2);
                }
            },
            legend: {
                enabled: false
            },
            exporting: {
                enabled: false
            },
            series: [{
                name: 'Slave data',
                data: []
            }]
        });
    });
});


</script>

app/views/rigs/_motor.html.erb
<li class="motor-widget" id="<%= widget['id'] %>" data-row="<%= widget['row'] %>" data-col="<%= widget['col'] %>" data-sizex="<%= widget['size_x'] %>" data-sizey="<%= widget['size_y'] %>">
  <% if SlaveModule.find(widget['settings'].select{|s| s['name'] == 'slaveModule'}.first['value']).slave_datas.last.data.to_i == 1 %>
    <img class="motor-switch" data-on="true" src="/widgets/ui/switch_on.png" />
  <% else %>
    <img class="motor-switch" data-on="false" src="/widgets/ui/switch_off.png" />
  <% end %>
  <h4><%= widget['settings'].select{|s| s['name'] == 'name'}.first['value'] %></h4>
</li>

<script>
  $('.motor-widget#<%= widget['id'] %> .motor-switch').on('click', function() {
    if ($(this).data('on') == true) {

      $.ajax({
        method: 'post',
        url: '/mqtt',
        data: {
          'rig_hash': '<%= @rig.rig_hash %>',
          's_address': '<%= SlaveModule.find(widget['settings'].select{|s| s['name'] == 'slaveModule'}.first['value']).s_addr %>',
          's_command': 0,
          's_value': 0
        }
      })

      $(this).attr('src', '/widgets/ui/switch_off.png');
      $(this).data('on', false);
    } else {

      $.ajax({
        method: 'post',
        url: '/mqtt',
        data: {
          'rig_hash': '<%=  @rig.rig_hash %>',
          's_address': '<%= SlaveModule.find(widget['settings'].select{|s| s['name'] == 'slaveModule'}.first['value']).s_addr %>',
          's_command': 1,
          's_value': 0
        }
      })
      $(this).attr('src', '/widgets/ui/switch_on.png')
      $(this).data('on', true);
    }
  });
</script>

app/views/rigs/edit.html.erb
<div class="container">
  <h1>Configuring Rig Controller</h1>

  <%= render 'form' %>

  <hr>
  <%= link_to 'Show', @rig, class: 'btn btn-default' %>
  <%= link_to 'Back', rigs_path, class: 'btn btn-default' %>
</div>

app/views/rigs/experiments.html.erb
<div class="container">
  <h1 class="text-center">Experiments</h1>
  <hr>

  <% @experiments.each do |experiment| %>
    <div class="experiment thumbnail col-md-3 text-center">
      <h3><a href="<%= rig_session_path(experiment.id) %>"><%= experiment.title %></a></h3>
      <p><small>created by <%= experiment.user.email %></small></p>
      <p><small><%= experiment.description%></small></p>
    </div>
  <% end %>
</div>

app/views/rigs/index.html.erb
<div class="container">

<h1 class="text-center">My Things</h1>
<hr>

<%= link_to 'Register Thing Gateway', new_rig_path, class: 'btn btn-primary' %>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rigs.each do |rig| %>
      <tr>
        <td><%= rig.title %></td>
        <td><%= rig.rig_type.titleize %></td>
        <td><%= rig.description %></td>
        <td><%= rig.published ? 'Published' : 'Private' %></td>
        <td><%= link_to 'Show', rig %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/rigs/new.html.erb
<div class="container">
  <h1>Register Thing Controllers</h1>
  <p>Please select your rig controller from the list of pending ones below:</p>
  <small>Note that it is intended that rig controllers will be uniquely identified on production.</small>


  <h2>Pending Thing Controllers</h2>

  <table class="table">
    <thead>
      <th>Thing ID</th>
      <th>Connected at</th>
      <th>Actions</th>
    </thead>
    <tbody>
    <% @pending_rigs.each do |rig| %>
      <tr>
        <td><%= rig.rig_hash %></td>
        <td><%= rig.created_at %></td>
        <td>
          <a class="btn btn-success sync-btn" id="<%= rig.id %>">Sync</a>
          <a class="btn btn-default">Ping</a>
        </td>
      </tr>
    <% end %>
    </tbody>

  </table>

  <%= link_to 'Back', rigs_path, class: 'btn btn-danger' %>
</div>

<div class="modal fade" id="settings-modal" tabindex="-1" role="dialog" aria-labelledby="settings-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Syncing Thing Controller</h4>
      </div>
      <div class="modal-body centerize">
        <div class="syncing">
          <%= image_tag '/spinner.gif'%>
          <hr>
          <p>Please hold the sync button on your rig controller for 5 to 10 seconds...</p>
        </div>
        <div class="synced" style="display: none">
          <p>Thing Controller successfully registered! Click the button below to start configuring it...</p>
          <a class="btn btn-lg btn-primary configure-btn">Configure Thing Controller</a>
        </div>
      </div>
      <div class="modal-footer">
        <a class="btn btn-default">Ping</a>
        <button type="button" class="btn btn-danger" data-dismiss="modal" id="close-settings">Cancel</button>
      </div>
    </div>
  </div>
</div>

<script>
  $('.sync-btn').on('click', function() {
    var id = $(this).attr('id');
    $('.modal').modal();
    $('.synced').hide();
    $('.syncing').show();
     setTimeout(function() {
       $('.syncing').hide();
       $('.configure-btn').attr('href', '/rigs/' + id + '/edit');
       $('.synced').show();
     }, 5000)
  });
</script>

app/views/rigs/show.html.erb
<div class="container">
  <h1>
    <%= @rig.title %>
    <small>(<%= @rig.rig_type.titleize %>)</small>
  </h1>
  <p>
    <label>Description:</label>
    <%= @rig.description %>
  </p>

  <p>
    <label>Status:</label>
    <% if @rig.published %>
      Published
      <small><a>Unpublish</a></small>
    <% else %>
      Private
      <small><a>Publish</a></small>
    <% end %>
  </p>

  <p>
    <label>Password Protected:</label>
    <%= @rig.password.present?.to_s.titleize %>
  </p>

  <hr>
  <div class="buttons">
    <%= link_to 'Configure', edit_rig_path(@rig), class: 'btn btn-primary btn-lg' %>
    <%= link_to 'UI Designer', ui_designer_path(@rig), class: 'btn btn-warning btn-lg' %>
  </div>
  <hr>


  <h2>Slave Modules</h2>
  <table class="table">
    <thead>
      <th>Address</th>
      <th>Type</th>
      <th>Connected At</th>
    </thead>
    <tbody>
      <% @slave.each do |slave| %>
      <tr>
        <td><%= slave.s_addr %></td>
        <td><%= slave.s_type.titleize %></td>
        <td><%= slave.created_at %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rigs/ui_designer.html.erb
<%= javascript_tag do %>
	window.definedWidgets = JSON.parse('<%= raw @defined_widgets.to_json %>');
  <% if @rig.ui_json.nil? %>
    window.uiJSON = {};
  <% else %>
    window.uiJSON = JSON.parse('<%= raw @rig.ui_json.gsub("'", %q(\\\')) %>');
  <% end %>
<% end %>

<div>

  <div class="col-md-2" id="side-bar">
    <h3>Wigdets</h3>

    <small>Drag and drop the widgets onto the canvas on the right.</small>

    <hr>

    <% @defined_widgets.each do |key, value| %>
      <div class="row">
        <img class="thumbnail defined-widget" src="<%= value[:image] %>" id="<%= key %>"/>
      </div>
    <% end %>

    <hr>

    <div class="row centerize">
      <%= simple_form_for(@rig) do |f| %>
        <%= f.hidden_field :ui_json %>
      <% end %>

      <a class="btn btn-success btn-lg" id="save-ui">Save</a>
      <a class="btn btn-danger btn-lg" href="<%= rig_path(@rig) %>">Cancel</a>
    </div>
  </div>


  <div class="col-md-10">
    <div class="gridster thumbnail" id="canvas">
      <!-- widgets goes inside the ul -->
      <ul>
      </ul>

    </div>
  </div>

</div>

</div>

<div class="modal fade" id="settings-modal" tabindex="-1" role="dialog" aria-labelledby="settings-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Settings</h4>
      </div>
      <div class="modal-body">
        <form id="switch-form" style="display: none;">
          <label for="slaveModule">Slave Module</label>
          <select name="slaveModule" class="form-control">
            <% @switchable_slaves.each do |s| %>
              <option value="<%= s.id %>"><%= "#{s.s_type.titleize} at address #{s.s_addr}" %></option>
            <% end %>
          </select>

          <label for="pin">Switch Port</label>
          <select name="pin" class="form-control">
            <% (3..13).to_a.each do |i| %>
              <option value="<%= i %>"><%= "Port #{i}" %></option>
            <% end %>
          </select>

          <label for="name">Name</label>
          <input name="name" class="form-control"></input>
        </form>

        <form id="chart-form" style="display: none;">
          <label for="slaveModule">Slave Module</label>
          <select name="slaveModule" class="form-control">
            <% @chartable_slaves.each do |s| %>
              <option value="<%= s.id %>"><%= "#{s.s_type.titleize} at address #{s.s_addr}" %></option>
            <% end %>
          </select>

					<label for="pin">Slave Port</label>
          <select name="pin" class="form-control">
            <% (0..3).to_a.each do |i| %>
              <option value="<%= i %>"><%= "Port #{i}" %></option>
            <% end %>
          </select>

          <label for="name">Name</label>
          <input name="name" class="form-control"></input>

          <label for="xAxis">X Axis</label>
          <input name="xAxis" class="form-control"></input>

          <label for="yAxis">Y Axis</label>
          <input name="yAxis" class="form-control"></input>

          <label for="period">Period</label>
          <input name="period" class="form-control" type="number"></input>

          <label for="interval">Interval</label>
          <input name="interval" class="form-control" type="number"></input>

          <label for="updateRate">Update Rate</label>
          <input name="updateRate" class="form-control" type="number"></input>

        </form>

				<form id="data-log-form" style="display: none;">
          <label for="slaveModule">Slave Module</label>
          <select name="slaveModule" class="form-control">
            <% @slave_modules.each do |s| %>
              <option value="<%= s.id %>"><%= "#{s.s_type.titleize} at address #{s.s_addr}" %></option>
            <% end %>
          </select>

					<label for="pin">Slave Port</label>
          <select name="pin" class="form-control">
            <% (0..13).to_a.each do |i| %>
              <option value="<%= i %>"><%= "Port #{i}" %></option>
            <% end %>
          </select>

          <label for="name">Name</label>
          <input name="name" class="form-control"></input>
        </form>

				<form id="value-form" style="display: none;">
          <label for="slaveModule">Slave Module</label>
          <select name="slaveModule" class="form-control">
            <% @slave_modules.each do |s| %>
              <option value="<%= s.id %>"><%= "#{s.s_type.titleize} at address #{s.s_addr}" %></option>
            <% end %>
          </select>

					<label for="pin">Slave Port</label>
          <select name="pin" class="form-control">
            <% (0..13).to_a.each do |i| %>
              <option value="<%= i %>"><%= "Port #{i}" %></option>
            <% end %>
          </select>

          <label for="name">Name</label>
          <input name="name" class="form-control"></input>
        </form>

        <form id="motor-form" style="display: none;">
          <label for="slaveModule">Slave Module</label>
          <select name="slaveModule" class="form-control">
            <% @motor_slaves.each do |s| %>
              <option value="<%= s.id %>"><%= "#{s.s_type.titleize} at address #{s.s_addr}" %></option>
            <% end %>
          </select>

          <label for="name">Name</label>
          <input name="name" class="form-control"></input>
        </form>

        <form id="servo-form" style="display: none;">
          <label for="slaveModule">Slave Module</label>
          <select name="slaveModule" class="form-control">
            <% @servo_slaves.each do |s| %>
              <option value="<%= s.id %>"><%= "#{s.s_type.titleize} at address #{s.s_addr}" %></option>
            <% end %>
          </select>

          <label for="name">Name</label>
          <input name="name" class="form-control"></input>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" id="close-settings">Close</button>
        <button type="button" class="btn btn-primary" id="save-settings">Save changes</button>
      </div>
    </div>
  </div>
</div>

<script>
  $(function() {

    var widgetNextIndex = 0;

    var gridster = $(".gridster ul").gridster({
      widget_margins: [10, 10],
      widget_base_dimensions: [250, 165],
      resize: {enabled: true},
      serialize_params: function ($w, wgd) {
        return {
          id: parseInt($($w).attr('id')),
          type: $($w).data('type'),
          settings: $($w).data('settings'),
          col: wgd.col,
          row: wgd.row,
          size_x: wgd.size_x,
          size_y: wgd.size_y
        };
      }
    }).data('gridster');

    $('.defined-widget').draggable({
      revert: true
    });

    $('#canvas').droppable({
      accept: '.defined-widget',
      drop: function(event, ui) {
        var widgetType = ui.draggable.attr('id');
        while ($('.widget-in#' + widgetNextIndex).length != 0) {
          widgetNextIndex++
        }
        addWidgetToCanvas(widgetType, widgetNextIndex);
      }
    });

    rebuildWidgetsFromJson();

    // bind the save button
    $('#save-ui').on('click', function() {
      // check that all the widgets have been configured
      if ($(".widget-in.unconfigured").length > 0) {
        alert('You must configure all widgets before saving.');
      } else {
      // generate the json string and submit the form
        $('#rig_ui_json').val(JSON.stringify(gridster.serialize()));
        $('form.edit_rig').submit();
      }
    });


    // FUNCTIONS

    function rebuildWidgetsFromJson() {
      if (window.uiJSON.length > 0) {
        $.each(window.uiJSON, function() {
          addWidgetToCanvas(this.type, this.id, this.size_x, this.size_y, this.col, this.row, this.settings);
        });

        // adjust the next indea for extra widgets
        widgetNextIndex = $('.widget-in').length;
      }
    }

    function addWidgetToCanvas(widgetType, index, size_x, size_y, col, row, settings) {
      // create and add the widget to the canvas
      if (typeof size_x == 'undefined') {
        gridster.add_widget(
          '<li class="widget-in" id="' + index + '" data-type="' + widgetType + '">' +
            '<a class="btn btn-danger pull-right delete-widget">Delete</a>' +
            '<a class="btn btn-default pull-right setting-widget">Settings</a>' +
            '<img src="' + window.definedWidgets[widgetType].image + '"/>' +
          '</li>');

        $('.widget-in#' + index).addClass('unconfigured');
      } else {
        gridster.add_widget(
          '<li class="widget-in" id="' + index + '" data-type="' + widgetType + '">' +
            '<a class="btn btn-danger pull-right delete-widget">Delete</a>' +
            '<a class="btn btn-default pull-right setting-widget">Settings</a>' +
            '<img src="' + window.definedWidgets[widgetType].image + '"/>' +
          '</li>', size_x, size_y, col, row);

        $('.widget-in#' + index).data('settings', settings);
      }

      // bind delete buttons
      $('.widget-in#' + index + ' .delete-widget').on('click', function() {
        gridster.remove_widget($(this).parent());
      })

      // bind settings buttons
      $('.widget-in#' + index + ' .setting-widget').on('click', function() {
        // setup the modal form fields and buttons
        $('.modal-body form').hide();
        $('#' + window.definedWidgets[widgetType].form).show();

        var currentId = $(this).parent().attr('id');

        // repopulate fields if defined
        document.getElementById(window.definedWidgets[widgetType].form).reset();
        var values = $(this).parent().data('settings');
        if (typeof values != 'undefined') {
          for (var i = 0; i < values.length; i++) {
            $("input[name='" + values[i].name + "']").val(values[i].value);
          }
        }

        $('#save-settings').data('widgetId', currentId);
        $('#save-settings').off('click');
        $('#save-settings').on('click', function() {
          // store json data to the widget
          var thisId = $(this).data('widgetId');
          var thisForm = $('#' + window.definedWidgets[widgetType].form);

          var formData = thisForm.serializeArray();
          $('.widget-in#' + thisId).data('settings', formData);
          $('.widget-in#' + thisId).removeClass('unconfigured');

          // reset the form
          document.getElementById(window.definedWidgets[widgetType].form).reset();

          // close the modal
          $('#settings-modal').modal('hide')
        });

        // show modal
        $('#settings-modal').modal();
      })
    }

  });



</script>